# Data parameters
FEATURES:
  - pm25
  - pm10
  - o3
  - no2
  - so2
  - co
  - temperature_c
  - humidity_percent
  - wind_speed_mps
TARGET: aqi
SEQUENCE_LENGTH: 30      # past days (for time series features if engineered)
TRAIN_TEST_SPLIT: 0.8

# Model parameters (XGBoost)
MODEL_TYPE: XGBRegressor


XGBOOST:
  n_estimators: 500
  learning_rate: 0.05
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

# Training parameters
EARLY_STOPPING: True
EARLY_STOPPING_ROUNDS: 50
EVAL_METRIC: rmse
MODEL_SAVE_PATH: models/xgb_aqi_model.pkl
