artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/samithcsachi/Air-Quality-Health-Alert-System/main/research/Air_Quality_Data.csv
  local_data_file: artifacts/data_ingestion/data/Air_Quality_Data.csv


data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data/Air_Quality_Data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data/Air_Quality_Data.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

 

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  report_path: artifacts/model_evaluation/metrics.json